/**
 * Workflow protocol v1 — the stable, versioned contract every surface speaks.
 *
 * One source of truth: these zod schemas produce the TypeScript types, the RPC contract (`../service/rpc.ts`),
 * the Gateway's request validation, and the published JSON Schemas (`docs/protocol/schemas/`, generated by
 * `script/protocol-schemas.ts`). Within v1 changes are additive only: new optional fields, new event types,
 * new error codes. A breaking change creates v2.
 *
 * Client rule (see docs/protocol/README.md): snapshot → subscribe → apply events whose `revision` is greater
 * than the snapshot's → on a gap, or on `resync.required`, re-read the snapshot.
 */
import { z } from "zod"

export const PROTOCOL_VERSION = 1 as const

// ---------------------------------------------------------------------------------------------------------------
// Shared pieces
// ---------------------------------------------------------------------------------------------------------------

export const Usage = z.object({
  tokens: z.object({
    input: z.number(),
    output: z.number(),
    reasoning: z.number(),
    cacheRead: z.number(),
    cacheWrite: z.number(),
  }),
  /** USD, as reported by OpenCode for the Unit sessions. */
  cost: z.number(),
})
export type Usage = z.infer<typeof Usage>

export function emptyUsage(): Usage {
  return { tokens: { input: 0, output: 0, reasoning: 0, cacheRead: 0, cacheWrite: 0 }, cost: 0 }
}

export function addUsage(into: Usage, add: Usage): Usage {
  return {
    tokens: {
      input: into.tokens.input + add.tokens.input,
      output: into.tokens.output + add.tokens.output,
      reasoning: into.tokens.reasoning + add.tokens.reasoning,
      cacheRead: into.tokens.cacheRead + add.tokens.cacheRead,
      cacheWrite: into.tokens.cacheWrite + add.tokens.cacheWrite,
    },
    cost: into.cost + add.cost,
  }
}

export const WorkflowErrorRecord = z.object({
  unit: z.string(),
  prompt: z.string(),
  subagent: z.string(),
  error: z.string(),
})
export type WorkflowErrorRecord = z.infer<typeof WorkflowErrorRecord>

export const ProtocolError = z.object({
  code: z.enum([
    "not_found",
    "conflict",
    "invalid_args",
    "invalid_state",
    "unauthorized",
    "forbidden",
    "rate_limited",
    "unsupported",
    "internal",
  ]),
  message: z.string(),
  retryable: z.boolean(),
  details: z.record(z.string(), z.unknown()).optional(),
})
export type ProtocolError = z.infer<typeof ProtocolError>
export type ProtocolErrorCode = ProtocolError["code"]

export class WorkflowProtocolError extends Error {
  readonly code: ProtocolErrorCode
  readonly retryable: boolean
  readonly details?: Record<string, unknown>
  constructor(
    code: ProtocolErrorCode,
    message: string,
    options: { retryable?: boolean; details?: Record<string, unknown> } = {},
  ) {
    super(message)
    this.name = "WorkflowProtocolError"
    this.code = code
    this.retryable = options.retryable ?? false
    this.details = options.details
  }
  toJSON(): ProtocolError {
    return {
      code: this.code,
      message: this.message,
      retryable: this.retryable,
      ...(this.details ? { details: this.details } : {}),
    }
  }
}

// ---------------------------------------------------------------------------------------------------------------
// Units
// ---------------------------------------------------------------------------------------------------------------

export const UnitStatus = z.enum(["queued", "running", "repairing", "succeeded", "failed", "stopped", "replayed"])
export type UnitStatus = z.infer<typeof UnitStatus>

export const ResultPath = z.enum(["text", "tool", "text-json", "extract", "replay"])
export type ResultPath = z.infer<typeof ResultPath>

export const UnitAttempt = z.object({
  turn: z.number(),
  path: ResultPath,
  ok: z.boolean(),
  error: z.string().optional(),
  /** Context for a successful attempt, e.g. that its usage is estimated. */
  note: z.string().optional(),
})
export type UnitAttempt = z.infer<typeof UnitAttempt>

export const Unit = z.object({
  unitId: z.string(),
  runId: z.string(),
  ordinal: z.number(),
  label: z.string().nullable(),
  subagent: z.string(),
  phase: z.string().nullable(),
  status: UnitStatus,
  /** The Unit session. Null until created, and for replayed Units that never ran in this Run. */
  sessionID: z.string().nullable(),
  /** The location (directory) the Unit session runs in — differs from the Run's for worktree Units. */
  location: z.string().nullable(),
  prompt: z.string(),
  model: z.object({ requested: z.string().nullable(), resolved: z.string().nullable() }),
  /** Whether the Unit asked for a typed result (`agent({ schema })`). */
  schema: z.boolean(),
  resultPath: ResultPath.nullable(),
  attempts: z.array(UnitAttempt),
  /** The Unit's answer: its text, or its structured value as JSON. Elided in bulk payloads (`outputElided`). */
  output: z.string().optional(),
  outputElided: z.boolean().optional(),
  error: z.string().optional(),
  usage: Usage,
  startedAt: z.number().nullable(),
  endedAt: z.number().nullable(),
})
export type Unit = z.infer<typeof Unit>

// ---------------------------------------------------------------------------------------------------------------
// Interactions
// ---------------------------------------------------------------------------------------------------------------

export const InteractionQuestion = z.object({
  header: z.string(),
  prompt: z.string(),
  options: z.array(z.object({ label: z.string(), description: z.string() })),
  multiple: z.boolean(),
  custom: z.boolean(),
})
export type InteractionQuestion = z.infer<typeof InteractionQuestion>

export const InteractionKind = z.enum(["question", "permission", "approval"])
export type InteractionKind = z.infer<typeof InteractionKind>

/**
 * Who raised it: `script` (`ctx.ask`), `agent` (a Unit's model called `question`), `permission` (a Unit's
 * tool call needs a permission decision), `engine` (the engine itself, e.g. inline-run approval).
 */
export const InteractionOrigin = z.enum(["script", "agent", "permission", "engine"])
export type InteractionOrigin = z.infer<typeof InteractionOrigin>

export const PermissionDetail = z.object({
  action: z.string(),
  resources: z.array(z.string()),
  save: z.array(z.string()),
  requestID: z.string(),
})
export type PermissionDetail = z.infer<typeof PermissionDetail>

export const ApprovalDetail = z.object({
  sha256: z.string(),
  bytes: z.number(),
  /** The first lines of the inline source, for a human to judge. */
  preview: z.string(),
  requestingSessionID: z.string(),
})
export type ApprovalDetail = z.infer<typeof ApprovalDetail>

/** A native OpenCode form (a `question` the engine could not intercept). Only a client with the form API answers it. */
export const FormDetail = z.object({ formID: z.string() })
export type FormDetail = z.infer<typeof FormDetail>

const InteractionBase = z.object({
  interactionId: z.string(),
  runId: z.string(),
  unitId: z.string().nullable(),
  kind: InteractionKind,
  origin: InteractionOrigin,
  sessionID: z.string(),
  phase: z.string().nullable(),
  /** The form. Permission and approval interactions carry one synthesized question with their options. */
  questions: z.array(InteractionQuestion),
  permission: PermissionDetail.optional(),
  approval: ApprovalDetail.optional(),
  form: FormDetail.optional(),
  raisedAt: z.number(),
})

export const PendingInteraction = InteractionBase.extend({
  /** When automation takes it back; null means no deadline (the default). */
  graceEndsAt: z.number().nullable(),
})
export type PendingInteraction = z.infer<typeof PendingInteraction>

export const ResolvedInteraction = InteractionBase.extend({
  answers: z.array(z.array(z.string())),
  by: z.enum(["human", "automation"]),
  outcome: z.enum(["answered", "rejected", "cancelled"]).optional(),
  resolvedAt: z.number(),
})
export type ResolvedInteraction = z.infer<typeof ResolvedInteraction>

// ---------------------------------------------------------------------------------------------------------------
// Runs
// ---------------------------------------------------------------------------------------------------------------

export const RunStatus = z.enum(["queued", "running", "succeeded", "failed", "stopped", "interrupted"])
export type RunStatus = z.infer<typeof RunStatus>

export const Provenance = z.enum(["durable", "inline"])
export type Provenance = z.infer<typeof Provenance>

export const WorkflowIdentity = z.object({
  /** Registry key for durable Workflows; null for inline ones. */
  key: z.string().nullable(),
  name: z.string(),
  description: z.string(),
  provenance: Provenance,
})
export type WorkflowIdentity = z.infer<typeof WorkflowIdentity>

export const Run = z.object({
  runId: z.string(),
  workflow: WorkflowIdentity,
  /** The project directory the Run belongs to (its OpenCode location). */
  location: z.string(),
  parentSessionID: z.string(),
  status: RunStatus,
  /** True while at least one interaction waits on a person. */
  waiting: z.boolean(),
  background: z.boolean(),
  phases: z.array(z.string()),
  phasesDeclared: z.boolean(),
  currentPhase: z.string().nullable(),
  units: z.array(Unit),
  logs: z.array(z.string()),
  errors: z.array(WorkflowErrorRecord),
  interactions: z.array(PendingInteraction),
  resolved: z.array(ResolvedInteraction),
  usage: Usage,
  /** Output tokens counted against the advisory (or hard) budget. */
  tokensSpent: z.number(),
  budget: z.object({ total: z.number().nullable(), hard: z.boolean() }),
  startedAt: z.number(),
  endedAt: z.number().nullable(),
  /** A short rendering of the Run's result, once it has one. The full value is `runs.result`. */
  resultPreview: z.string().nullable(),
  /** The Run this one resumed, if any. */
  resumeOf: z.string().nullable(),
  /** Why the Run failed or stopped (null while running and on success). Unit failures are in `errors`. */
  error: z.string().nullable().optional(),
  /** Retention bookkeeping for the Unit sessions. */
  cleanup: z.enum(["none", "pending", "done"]),
  revision: z.number(),
})
export type Run = z.infer<typeof Run>

export const LibraryEntry = z.object({
  runId: z.string(),
  workflow: WorkflowIdentity,
  location: z.string(),
  parentSessionID: z.string(),
  status: RunStatus,
  waiting: z.boolean(),
  units: z.number(),
  settledUnits: z.number(),
  failedUnits: z.number(),
  phases: z.array(z.string()),
  phasesDeclared: z.boolean(),
  currentPhase: z.string().nullable(),
  usage: Usage,
  tokensSpent: z.number(),
  startedAt: z.number(),
  endedAt: z.number().nullable(),
  live: z.boolean(),
})
export type LibraryEntry = z.infer<typeof LibraryEntry>

export const WorkflowListing = z.object({
  key: z.string(),
  name: z.string(),
  description: z.string(),
  whenToUse: z.string().nullable(),
  phases: z.array(z.object({ title: z.string(), detail: z.string().nullable() })),
  args: z.record(z.string(), z.unknown()).nullable(),
  path: z.string(),
  scope: z.string(),
})
export type WorkflowListing = z.infer<typeof WorkflowListing>

// ---------------------------------------------------------------------------------------------------------------
// Events
// ---------------------------------------------------------------------------------------------------------------

/** A Run without its growing collections — what `run.updated` carries. */
export const RunHeader = Run.omit({ units: true, logs: true, interactions: true, resolved: true })
export type RunHeader = z.infer<typeof RunHeader>

export const EventType = z.enum([
  "run.started",
  "run.updated",
  "run.ended",
  "unit.updated",
  "interaction.pending",
  "interaction.resolved",
  "activity.appended",
  "library.changed",
  "resync.required",
])
export type EventType = z.infer<typeof EventType>

export const ActivityEntry = z.object({
  kind: z.enum(["log", "phase", "engine", "capability"]),
  message: z.string(),
  time: z.number(),
  unitId: z.string().nullable(),
})
export type ActivityEntry = z.infer<typeof ActivityEntry>

export const ProtocolEvent = z.object({
  protocol: z.literal(PROTOCOL_VERSION),
  /** Monotonic per service (per location). Gaps mean the client missed events. */
  seq: z.number(),
  /** Changes when the service restarts (seq starts again). A different epoch than the one you hold means resync. */
  epoch: z.string().optional(),
  time: z.number(),
  location: z.string(),
  /** Empty for location-wide events (`library.changed`, `resync.required`). */
  runId: z.string(),
  type: EventType,
  /** The Run's revision after this event (0 for location-wide events). */
  revision: z.number(),
  /**
   * - `run.started`: `Run` (outputs elided)
   * - `run.updated`, `run.ended`: `RunHeader`
   * - `unit.updated`: `Unit` (output elided when large)
   * - `interaction.pending`: `PendingInteraction`
   * - `interaction.resolved`: `ResolvedInteraction`
   * - `activity.appended`: `ActivityEntry`
   * - `library.changed`: `LibraryEntry`
   * - `resync.required`: `{ reason: string }`
   */
  data: z.unknown(),
})
export type ProtocolEvent = z.infer<typeof ProtocolEvent>

// ---------------------------------------------------------------------------------------------------------------
// Queries and commands (inputs/outputs shared by RPC and the Gateway)
// ---------------------------------------------------------------------------------------------------------------

export const InfoOutput = z.object({
  protocol: z.literal(PROTOCOL_VERSION),
  plugin: z.object({ name: z.string(), version: z.string() }),
  opencode: z.string(),
  location: z.string(),
  capabilities: z.array(z.string()),
  limits: z.object({
    maxUnits: z.number(),
    maxItemsPerCall: z.number(),
    maxUnitSteps: z.number(),
    /** Units in flight per Run. */
    maxConcurrentUnits: z.number().optional(),
    /** Runs executing at once across the process. */
    maxConcurrentRuns: z.number().optional(),
    providerConcurrency: z.record(z.string(), z.number()).optional(),
  }),
  gateway: z.object({ url: z.string().nullable() }),
})
export type InfoOutput = z.infer<typeof InfoOutput>

export const ListRunsInput = z.object({
  status: z.array(RunStatus).optional(),
  parentSessionID: z.string().optional(),
  search: z.string().optional(),
  since: z.number().optional(),
  limit: z.number().int().positive().max(500).optional(),
})
export type ListRunsInput = z.infer<typeof ListRunsInput>

export const ListRunsOutput = z.object({ runs: z.array(LibraryEntry) })
export type ListRunsOutput = z.infer<typeof ListRunsOutput>

export const RunRef = z.object({ runId: z.string() })
export const UnitRef = z.object({ runId: z.string(), unitId: z.string() })
export const InteractionRef = z.object({ runId: z.string(), interactionId: z.string() })

export const GetRunOutput = z.object({ run: Run, live: z.boolean() })
export type GetRunOutput = z.infer<typeof GetRunOutput>

export const GetUnitOutput = z.object({ unit: Unit })
export const GetResultOutput = z.object({ runId: z.string(), status: RunStatus, result: z.unknown() })

export const ListWorkflowsOutput = z.object({
  workflows: z.array(WorkflowListing),
  collisions: z.array(z.object({ key: z.string(), kept: z.string(), shadowed: z.string(), sameScope: z.boolean() })),
  failures: z.array(z.object({ path: z.string(), error: z.string() })),
})
export type ListWorkflowsOutput = z.infer<typeof ListWorkflowsOutput>

export const StartRunInput = z.object({
  /** Durable Workflow key. Exactly one of `name` or `source`. */
  name: z.string().optional(),
  /** Inline Workflow source (needs approval unless the project allows inline runs). */
  source: z.string().optional(),
  args: z.unknown().optional(),
  /** Session to attribute the Run to; defaults to a new session titled after the Workflow. */
  parentSessionID: z.string().optional(),
  requestId: z.string().optional(),
})
export type StartRunInput = z.infer<typeof StartRunInput>

export const StartRunOutput = z.object({ runId: z.string() })

export const ReplyInteractionInput = z.object({
  runId: z.string(),
  interactionId: z.string(),
  /** One entry per question, each a list of chosen labels (or free text where `custom`). */
  answers: z.array(z.array(z.string())),
})
export type ReplyInteractionInput = z.infer<typeof ReplyInteractionInput>

export const ResumeRunInput = z.object({
  runId: z.string(),
  /** Re-run Units that failed or were stopped instead of replaying them as failures. Default true. */
  rerunFailed: z.boolean().optional(),
})

export const SaveRunInput = z.object({ runId: z.string(), name: z.string().optional() })
export const SaveRunOutput = z.object({ key: z.string(), path: z.string() })

export const CleanupRunOutput = z.object({ deleted: z.number(), pending: z.number() })

export const AttachInput = z.object({
  surface: z.string(),
  /** The TUI session in view, so the engine can prefer that surface for its Runs. */
  sessionID: z.string().optional(),
  ttlMs: z.number().int().positive().max(120_000).optional(),
})

export const OkOutput = z.object({ ok: z.literal(true) })

export const ActivityOutput = z.object({ entries: z.array(ActivityEntry) })

export const EventsSinceInput = z.object({
  after: z.number().optional(),
  /** The epoch `after` belongs to. A different epoch answers `complete: false`. */
  epoch: z.string().optional(),
})
export const EventsSinceOutput = z.object({
  events: z.array(ProtocolEvent),
  /** False when `after` is older than the retained window: re-read snapshots. */
  complete: z.boolean(),
  latest: z.number(),
  epoch: z.string().optional(),
})

/** One message of a Unit's session, simplified for display. Large inputs and outputs are clipped. */
export const TranscriptPart = z.object({
  kind: z.enum(["text", "reasoning", "tool", "other"]),
  text: z.string().optional(),
  tool: z
    .object({
      name: z.string(),
      status: z.string(),
      input: z.string().optional(),
      output: z.string().optional(),
      error: z.string().optional(),
    })
    .optional(),
})
export type TranscriptPart = z.infer<typeof TranscriptPart>

export const TranscriptMessage = z.object({
  role: z.enum(["user", "assistant", "system", "other"]),
  parts: z.array(TranscriptPart),
  model: z.string().nullable(),
  error: z.string().nullable(),
})
export type TranscriptMessage = z.infer<typeof TranscriptMessage>

export const GetTranscriptOutput = z.object({
  sessionID: z.string(),
  messages: z.array(TranscriptMessage),
  /** True when some parts were clipped for size. */
  clipped: z.boolean(),
})
export type GetTranscriptOutput = z.infer<typeof GetTranscriptOutput>

/** Every schema published as JSON Schema, by file name. */
export const PUBLISHED_SCHEMAS = {
  Usage,
  Unit,
  PendingInteraction,
  ResolvedInteraction,
  Run,
  RunHeader,
  LibraryEntry,
  WorkflowListing,
  ActivityEntry,
  ProtocolEvent,
  ProtocolError,
  InfoOutput,
  ListRunsInput,
  StartRunInput,
  ReplyInteractionInput,
  TranscriptMessage,
  GetTranscriptOutput,
} as const
